version: "3"

services:
  db:
    container_name: db
    image: postgres:11.4-alpine
    environment:
      - TZ=Asia/Tokyo
    volumes:
      - ./api/tmp/db:/var/lib/postgresql/data

  api:
    container_name: api
    build: api/
    volumes:
      - ./api:/app
    depends_on:
      - db
    ports:
      - "3000:3000"
    command: bash -c "crond && exec bundle exec rails s -b '0.0.0.0'"

  frontend:
    container_name: frontend
    build: frontend/
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - "3001:3000"
      - "3002:3001"
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: sh -c "yarn && yarn start"