default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  database: wont1on1
  password:
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
  